language: c

install:
  - sudo apt-get install cmake mono-devel mono-gmcs

script:
  - xbuild source/Lucene.Net.Linq.sln
  - nunit-console ./source/Lucene.Net.Linq.Tests/bin/Debug/Lucene.Net.Linq.Tests.dll -exclude Integration,NotWorkingOnMono
